@startuml Horizontal_Condition

title Horizontal Condition - Activity Diagram

start

:click on shopping cart;

if (Payment Method == "Use Credit Card") then (yes)
  :Insert Credit card number;
  :Insert expiration date;
  :Insert pin;
elseif (Payment Method == "Use Paypal") then (yes)
  :Link to Paypal;
  :Insert username/password;
elseif (Payment Method == "Use Venmow") then (yes)
  :Insert code;
  :Insert username;
elseif (Payment Method == "Use Gift Card") then (yes)
  :Insert 16 digits;
  :Insert expiration date;
else
  :Invalid Payment Method;
endif

:Authorizing;
:Pending Payment;
:Payment Complete;

stop

@enduml