@startgantt projectplan

printscale weekly zoom 4

title Projektplan mit Vorgängen, Meilensteinen und Abhängigkeiten

Project starts 2024-01-07

-- Designphase --
[Prototype design] starts at 2024-01-18
[Prototype design] lasts 10 days

-- Entwicklungsphase --
[Develop prototype] starts at [Prototype design]'s end
[Develop prototype] lasts 15 days
[Develop completed] starts at [Develop prototype]'s end
[Develop completed] happens at [Develop prototype]'s end

-- Test phase --
2024-02-01 to 2024-02-22 are named [Paralell Testing]
[Test prototype] starts at 2024-02-10
[Test prototype] lasts 15 days
[Test completed] starts at [Test prototype]'s end
[Test completed] happens at [Test prototype]'s end

-- Deployment phase --
2024-02-12 to 2024-02-22 are named [When is deployment?]
[PROD Deployment] starts at [Test completed]'s end
[PROD Deployment] lasts 2 days

[Prototype design] is 100% completed
[Develop prototype] is 100% completed
[Test prototype] is 100% completed

Separator just at [Develop prototype]'s end

@endgantt