@startuml usecase model

title Usecase Diagramm

Actor "Actor 2" as actor2
note left of actor2
    <b><color:black><size:14>Actor 2
    Lorem ipsum dolor sit amet,
    consetetur sadipscing elitr, sed diam
    nonumy eirmod tempor
    invidunt ut labore et dolore magna
end note

Actor "Actor 1" as actor1
note left of actor1
    <b><color:black><size:14>Actor 1
    Lorem ipsum dolor sit amet,
    consetetur sadipscing elitr, sed diam
    nonumy eirmod tempor
    invidunt ut labore et dolore magna
end note

rectangle "System A" {
    UseCase (Use first case) as UC1
}
note right of UC1
    This is a description of a UseCase ...
    Lorem ipsum dolor <i>sit amet,
    consetetur sadipscing elitr, sed diam
    nonumy eirmod tempor
    invidunt ut labore et dolore magna
    aliquyam erat, sed diam voluptua.
    At vero eos et accusam et
end note

actor1  -- UC1
actor2 -- UC1

rectangle  "System B" {
    UseCase (Use second case) as UC2
    UseCase (Use third case) as UC3
}
actor2 -- UC2
actor2 -- UC3

UseCase (Old Usecase) <<External>> as UC4
UseCase (Other Usecase) <<External>> as UC5
UC3 ..|> UC4 : <<include>>
UC2 <|.. UC5 : <<extends>>

@enduml