''Define colors in doubleSlash corporate identity
!define DS_BLUE           #00A5E1
!define DS_LIGHTBLUE      #D7E9F4
!define DS_ORANGE         #FF9F00
!define DS_LIGHTGREY      #C6C6C6
!define DS_GREY           #7A7A7A
!define DS_DARKGREY       #515151

!define SUPERLIGHTGREY    #F8F8F8
!define STEELBLUE25       #374656
!define STEELBLUE40       #8A9DB3
!define BLACK50           #7F7F7F
!define BLACK25           #404040
!define LIGHTGREEN        #D5E8D4

!define TIPBGCOLOR       #FFF6E7
!define TIPBORDERCOLOR   #FFD999

!define FONTNAME          "Helvetica"