@startuml
class Haus {
  +haustuer: Haustuer
  +stockwerke: Stockwerk[3]
}

class Haustuer {
  -farbe: String
  +oeffnen()
  +schliessen()
}

class Stockwerk {
  -nummer: int
  +aufzugRufen()
}

Haus "1" -- "1" Haustuer: besitzt
Haus "1" -- "3" Stockwerk: hat
@enduml