!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/doubleslash-colordefs.puml

<style>
ganttDiagram {

  task {
    FontName FONTNAME
    FontSize 12
    BackGroundColor DS_LIGHTBLUE
    LineColor DS_BLUE
	Padding 2
  }

  timeline {
    FontName FONTNAME
	  BackgroundColor SUPERLIGHTGREY
	}

	milestone {
		FontColor BLACK25
		FontSize 14
		FontStyle normal
		BackGroundColor DS_BLUE
		LineColor DS_BLUE
		LineThickness 5.0
		Margin 5
	}

	note {
		FontColor black
		FontSize 10
		LineColor DS_LIGHTGREY 
	}
	closed {
		BackgroundColor SUPERLIGHTGREY
		FontColor DS_DARKGREY
	}

	Arrow {
		LineColor DS_GREY
		LineThickness 1.5
		Arrowstyle dotted
	}

	
}
</style>



