!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-general.puml

' Actor
'=================================================================
skinparam ActorBorderColor DS_LIGHTGREY
skinparam ActorBackgroundColor DS_LIGHTGREY
skinparam ActorBorderThickness 3.5
skinparam ActorFontName FONTNAME

skinparam maxMessageSize 100
skinparam ParticipantPadding 50
skinparam SequenceParticipantBorderThickness 0.0

skinparam Padding 6

' Sequence
'=================================================================
skinparam Sequence {

    LifeLineBackgroundColor DS_BLUE
    LifeLineBorderColor DS_BLUE
    LifeLineBorderThickness 0.0

    GroupBackgroundColor SUPERLIGHTGREY
    ReferenceBackgroundColor DS_LIGHTGREY

    ParticipantBackgroundColor DS_LIGHTBLUE
    ParticipantBorderColor DS_BLUE
    ParticipantFontColor DS_DARKGREY
    ParticipantFontSize 12

    DividerBorderThickness .5
    DividerFontSize 10
    ArrowColor DS_GREY
    ArrowFontSize 11

}

