!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-general.puml

<style>
node {
    Padding 10
    Margin 10
    HorizontalAlignment center
    LineThickness 0.0
    BackgroundColor #D7E9F4
    FontSize 12
}
leafNode {
    Fontsize 11
    Padding 1
    Margin 1
    BackgroundColor white
}
</style>
