!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-general.puml

'allowmixing 'if flag is set, different diagram types could mixed up
hide circle
hide empty members
hide stereotype
left to right direction
skinparam Ranksep 30

skinparam DefaultTextAlignment left
skinparam Linetype polyline

' Class styling, also works for other class stereotypes like Entity, ...
'=================================================================
skinparam Class {
    BackgroundColor DS_LIGHTBLUE
    BorderColor DS_BLUE
    BorderThickness 0

    BackgroundColor<<external>> SUPERLIGHTGREY
    BorderColor<<external>> DS_GREY
    BorderThickness<<external>> 0

    AttributeFontName FONTNAME
    AttributeFontSize 12
    AttributeFontColor black

    FontName FONTNAME
    FontSize 15
    FontColor black
    Fontstyle bold
}

