'Include this theme with:
!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-general.puml

' Actor
'=================================================================
skinparam ActorBorderColor DS_LIGHTGREY
skinparam ActorBackgroundColor DS_LIGHTGREY
skinparam ActorBorderThickness 4.0
skinparam ActorFontName FONTNAME


' Usecase
'=================================================================
skinparam UsecaseBackgroundColor DS_LIGHTBLUE
skinparam UsecaseBorderColor DS_BLUE
skinparam UsecaseBorderThickness 1.5
skinparam UseCaseFontName FONTNAME

skinparam UsecaseBackgroundColor<<External>> DS_LIGHTGREY
skinparam UsecaseBorderColor<<External>> DS_LIGHTGREY
