!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-general.puml

!pragma layout smetana
left to right direction
hide stereotypes

skinparam Linetype ortho
skinparam ComponentStyle rectangle

skinparam ComponentBorderThickness 0
skinparam ComponentBackgroundColor DS_LIGHTBLUE
skinparam ComponentFontColor black
skinparam ComponentBorderColor DS_BLUE

skinparam RectangleBackgroundcolor transparent
skinparam RectangleBorderColor DS_BLUE
skinparam RectangleBorderThickness 1
skinparam RectangleBorderStyle solid
skinparam RectangleFontColor black
skinparam RectangleFontStyle normal

' Summary Table
' *C5 Level*	*Stereotype*    *Description*
' Context	    <<context>>	    System in its environment
' Container	    <<container>>	Applications/services/databases
' Component	    <<component>>	Major logical parts inside a container
' Module	    <<module>>	    Groupings of code/packages/namespaces/subsystems
' Code          <<code>>	    Classes, files, functions, methods

' Define colors for each C4+M level
!define CONTEXT_BG #FFFFFF
!define CONTAINER_BG #EEF8FE
!define COMPONENT_BG #D7E9F4
!define MODULE_BG #AFC1C7
!define CODE_BG #84999F

' Context Level
skinparam RectangleBackgroundColor<<context>> CONTEXT_BG
skinparam RectangleBorderColor<<context>> DS_BLUE
skinparam RectangleFontColor<<context>> black

' Container Level  
skinparam RectangleBackgroundColor<<container>> CONTAINER_BG
skinparam RectangleBorderColor<<container>> none
skinparam RectangleFontColor<<container>> black

' Component Level
skinparam RectangleBackgroundColor<<component>> COMPONENT_BG
skinparam RectangleBorderColor<<component>> none
skinparam RectangleFontColor<<component>> black

' Module Level
skinparam RectangleBackgroundColor<<module>> MODULE_BG
skinparam RectangleBorderColor<<module>> none
skinparam RectangleFontColor<<module>> black

' Code Level
skinparam RectangleBackgroundColor<<code>> CODE_BG
skinparam RectangleBorderColor<<code>> none
skinparam RectangleFontColor<<code>> white

skinparam PackageBackgroundColor ALICEBLUE
skinparam PackageBorderColor DS_BLUE
skinparam PackageBorderThickness 0
skinparam PackageFontColor black
skinparam PackageFontsize 14

' Agent shapes ----------------------------
skinparam AgentBackgroundcolor DS_LIGHTBLUE
skinparam AgentFontColor black
skinparam AgentBorderThickness 0
skinparam AgentBackgroundcolor<<external>> SUPERLIGHTGREY
skinparam AgentFontColor<<external>> black
skinparam AgentBorderThickness<<external>> 0

skinparam DatabaseBackgroundcolor DS_LIGHTBLUE
skinparam DatabaseBorderThickness 0.0
skinparam DatabaseBackgroundcolor<<external>> SUPERLIGHTGREY
skinparam DatabaseBorderThickness<<external>> 0

skinparam ArrowThickness 1.5

skinparam interfaceBackgroundColor DS_BLUE
skinparam interfaceBorderColor DS_BLUE
skinparam interfaceBorderThickness 2
skinparam interfaceFontColor black

skinparam interfaceBorderColor<<external>> DS_GREY
skinparam interfaceBackgroundColor<<external>> DS_GREY


