'Include this theme with:
'!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash.puml
!$PUML_THEME = "doubleslash"
!$THEME      = "doubleslash"

''Define colors in doubleSlash corporate identity
!define DS_BLUE           #00A5E1
!define DS_LIGHTBLUE      #D7E9F4
!define DS_ORANGE         #FF9F00
!define DS_LIGHTGREY      #C6C6C6
!define DS_GREY           #7A7A7A
!define DS_DARKGREY       #515151

!define SUPERLIGHTGREY    #F8F8F8
!define STEELBLUE25       #374656
!define STEELBLUE40       #8A9DB3
!define BLACK50           #7F7F7F
!define BLACK25           #404040
!define LIGHTGREEN        #D5E8D4

!define TIPBGCOLOR       #FFF6E7
!define TIPBORDERCOLOR   #FFD999

!define FONTNAME          "Helvetica"

'allowmixing 'if flag is set, different diagram types could mixed up
show circle 
hide empty members
hide stereotype

skinparam Shadowing false
skinparam Padding 2
skinparam Roundcorner 16
skinparam backgroundColor white
skinparam defaultFontName FONTNAME
skinparam defaultFontSize 12

' Title
'=================================================================
skinparam TitleFontSize 18
skinparam TitleFontName FONTNAME
skinparam TitleFontColor DS_DARKGREY

' Note 
'=================================================================
'skinparam NoteBackgroundColor TIPBGCOLOR
'skinparam NoteBorderColor TIPBORDERCOLOR
'skinparam NoteBorderThickness 0.3
skinparam NoteBackgroundColor transparent
skinparam NoteBorderThickness 0.0
skinparam NoteFontColor DS_GREY
skinparam NoteFontSize 11
skinparam NoteShadowing true

' Rectangle
'=================================================================
skinparam RectangleFontColor DS_GREY
skinparam RectangleBackgroundColor SUPERLIGHTGREY
skinparam RectangleBorderColor DS_DARKGREY
skinparam RectangleFontSize 14

' Package
'=================================================================
skinparam PackageFontColor DS_GREY
skinparam PackageBackgroundColor SUPERLIGHTGREY
skinparam PackageBorderColor DS_DARKGREY
skinparam PackageFontSize 14

' Arrow
'=================================================================
skinparam ArrowColor DS_GREY
skinparam ArrowThickness 1.5
skinparam ArrowFontName FONTNAME
skinparam ArrowFontColor DS_GREY
skinparam ArrowFontStyle italic


' Rectangle
'=================================================================
skinparam RectangleBorderThickness 0.5
skinparam RectangleBorderColor DS_GREY
skinparam RectangleBackgroundColor SUPERLIGHTGREY


' Actor
'=================================================================
skinparam ActorBorderColor DS_LIGHTGREY
skinparam ActorBackgroundColor DS_LIGHTGREY
skinparam ActorBorderThickness 3.5
skinparam ActorFontName FONTNAME


' Usecase
'=================================================================
skinparam UsecaseBackgroundColor DS_LIGHTBLUE
skinparam UsecaseBorderColor STEELBLUE40
skinparam UsecaseBorderThickness 1.5
skinparam UsecaseBackgroundColor<<External>> DS_LIGHTGREY
skinparam UsecaseBorderColor<<External>> DS_LIGHTGREY

' Class
'=================================================================
skinparam ClassBackgroundColor DS_LIGHTBLUE
skinparam ClassFontColor DS_DARKGREY
skinparam ClassFontSize 12
skinparam ClassBorderColor STEELBLUE40
skinparam ClassBorderThickness 1.5

' Activity
'=================================================================
skinparam ActivityStartColor DS_DARKGREY
skinparam ActivityEndColor DS_DARKGREY
skinparam ActivityBackgroundColor DS_LIGHTBLUE
skinparam ActivityBorderColor STEELBLUE40
skinparam ActivityBorderThickness 1.5
skinparam ActivityDiamondBorderColor DS_ORANGE
skinparam ActivityDiamondBackgroundColor DS_ORANGE
skinparam ActivityDiamondFontColor DS_DARKGREY
skinparam ActivityDiamondFontName FONTNAME
skinparam conditionStyle diamond



' Sequence
'=================================================================
skinparam SequenceLifeLineBackgroundColor DS_LIGHTGREY
skinparam SequenceLifeLineBorderColor DS_LIGHTGREY
skinparam SequenceGroupBackgroundColor SUPERLIGHTGREY
skinparam SequenceReferenceBackgroundColor DS_LIGHTGREY

' Component
'=================================================================
skinparam ComponentBorderColor DS_BLUE 
skinparam ComponentBackgroundColor DS_LIGHTBLUE


