''Define colors in doubleSlash corporate identity
!define DS_BLUE           #00A5E1
!define DS_LIGHTBLUE      #D7E9F4
!define DS_ORANGE         #FF9F00
!define DS_LIGHTGREY      #C6C6C6
!define DS_GREY           #7A7A7A
!define DS_DARKGREY       #515151

!define SUPERLIGHTGREY    #F8F8F8
!define STEELBLUE25       #374656
!define STEELBLUE40       #8A9DB3
!define BLACK50           #7F7F7F
!define BLACK25           #404040
!define LIGHTGREEN        #D5E8D4

!define TIPBGCOLOR       #FFF6E7
!define TIPBORDERCOLOR   #FFD999

!define FONTNAME          Arial

skinparam Shadowing false
skinparam Padding 2
skinparam Roundcorner 16
skinparam BackgroundColor white
skinparam DefaultFontName FONTNAME
skinparam DefaultFontColor black
skinparam DefaultTextAlignment center

' Title
'=================================================================
skinparam TitleFontSize 28
skinparam TitleFontName FONTNAME
skinparam TitleFontColor DS_DARKGREY
skinparam TitleFontStyle normal

' Note 
'=================================================================
'skinparam NoteBackgroundColor TIPBGCOLOR
'skinparam NoteBorderColor TIPBORDERCOLOR
'skinparam NoteBorderThickness 0.3
'skinparam NoteShadowing true
skinparam NoteBackgroundColor transparent
skinparam NoteBorderColor transparent
skinparam NoteBorderThickness 0.0
skinparam NoteFontColor black
skinparam NoteFontSize 11
skinparam NoteTextAlignment left

' Rectangle
'=================================================================
skinparam RectangleBackgroundColor SUPERLIGHTGREY
skinparam RectangleBorderColor DS_DARKGREY
skinparam RectangleBorderColor DS_GREY
skinparam RectangleBorderThickness 0.5

skinparam RectangleFontColor black
skinparam RectangleFontSize 14


' Package
'=================================================================
skinparam PackageFontColor DS_GREY
skinparam PackageBackgroundColor SUPERLIGHTGREY
skinparam PackageBorderColor DS_DARKGREY
skinparam PackageFontSize 14

' Arrow
'=================================================================
skinparam ArrowColor DS_GREY
skinparam ArrowThickness 1.5
skinparam ArrowFontName FONTNAME
skinparam ArrowFontColor black
skinparam ArrowFontStyle normal



