'Include this theme with:
!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-general.puml

!pragma layout smetana
hide stereotypes
left to right direction

skinparam padding 6
skinparam nodesep 28
skinparam ranksep 1

' Rectangle for system boundary
'=================================================================
skinparam RectangleBackgroundColor ALICEBLUE
skinparam RectangleBorderThickness 0.0
skinparam RectangleBorderStyle solid

' Usecase
'=================================================================
skinparam UsecaseBackgroundColor DS_LIGHTBLUE
skinparam UsecaseBorderThickness 0.0
skinparam UseCaseFontName FONTNAME

' External Usecase
skinparam UsecaseBackgroundColor<<External>> SUPERLIGHTGREY


