!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-general.puml

' Class styling, also works for other class stereotypes like Entity, ...
'=================================================================
skinparam Class {
    BackgroundColor DS_LIGHTBLUE
    BorderColor DS_BLUE
    BorderThickness 1.5

    BackgroundColor<<external>> SUPERLIGHTGREY
    BorderColor<<external>> DS_GREY
    BorderThickness<<external>> 1.0

    AttributeFontName FONTNAME
    AttributeFontSize 12
    AttributeFontColor BLACK25

    FontName FONTNAME
    FontSize 16
    FontColor BLACK25
}

skinparam ClassFontSize 16

