@startuml Ports

title Ports - Deployment Diagram

node Message

folder Servers{
  port p1
  port p2
  port p3
  portout p4
	component S1
	component S2
}


Message --> p1
Message --> p2
Message --> p3

cloud Output

p4 --> Output




@enduml