@startuml Systemmodel

title "System model with C4-Level 1-System context and 2-Containers"

' Definition of objects
rectangle "System context" {

    package "Container " {
        [Component 1]
        [Component 2]
    }
    interface "Interface 1" as IF1
    note top of IF1
        This is a short
        description of the interface
    end note
}

agent "Calling System" as No2<<external>>
agent "Other\nlegacy system" as LegacySystem<<external>>
database "External\ndatabase" as eDB<<external>>
interface "Interface 2" as IF2 <<external>>

IF1 <|-- [Component 1] : implements
IF2 <|-- LegacySystem : implements
No2 ~~> IF1 : use

[Component 1] ~~> eDB : use
[Component 2] ~~> IF2 : use
@enduml