@startmindmap Basic_Mind_Map

'Compatible with OrgMode 

* Solving \n Global \n Warming

** Eating differently
*** Vegan
*** Vegetarian
*** Less processed foods
*** Buy local food
** Travel
*** Bike more
*** Ride buses
*** Buy an electric car

left side

** Home
*** Energy audit
*** Use a cloths line
*** Add insulation
*** Get solar panels
** Be a role model
*** Vote
*** Encourage others
*** Teach your kids

@endmindmap