@startmindmap Colors_Remove_Box

<style>
mindmapDiagram {
  .green {
    BackgroundColor lightgreen
  }
  .rose {
    BackgroundColor #FFBBCC
  }
}
</style>

* Solving \n Global \n Warming <<rose>>

**[#lightgreen] Eating differently
***[#Orange] Vegan
***[#Orange] Vegetarian
***[#Orange] Less processed foods
***[#Orange] Buy local food
** Travel <<green>>
***[#Orange] Bike more
***[#Orange] Ride buses
***[#Orange] Buy an electric car

left side

** Home <<green>>
***[#Orange] Energy audit
***[#Orange] Use a cloths line
***[#Orange] Add insulation
***[#Orange] Get solar panels
**[#lightgreen] Be a role model
***_ Vote
***_ Encourage others
***_ Teach your kids

@endmindmap