@startmindmap Multilines

* Solving \n Global \n Warming
**[#lightgreen] Eating differently
***[#Orange] Vegan
***[#Orange] Vegetarian
***[#Orange] Less processed foods
***[#Orange] Buy local food
** Travel
***:-Bike more
-Skateboard more
-Walk more
;
***:-Ride buses
-Ride UBER
-Ride carpool
;
***:-Buy an electric car
-Buy an electric scooter
-Buy an electric skateboard
;

@endmindmap