@startuml activitymodel
!include ../puml-theme-doubleslash.puml

'You will find help on this page: https://plantuml.com/de/activity-diagram-beta
' left to right direction 'does not work with activity diagrams

title Aktivitätsdiagramm im //-Design

|SUPERLIGHTGREY|Swimlane 1|
start
  :Activity 1; 
  :Activity 2;
  (✉)
  -[dotted]->
note right 
Diese Notiz 
gibt eine 
Erläuterung des 
Zwischenzustandes
end note

|Swimlane 2|
if (Alles OKAY?) then
  -> nur zum Teil;
  :do more research;
else
  -> Ja;
  :do action; 
endif  

|Swimlane 1|
  :final execution;
end



@enduml