@startuml deployment
!include puml-theme-doubleslash.puml

left to right direction

interface Schnittstelle
skinparam nodesep 25
skinparam Ranksep 1

class Klasse {
  - Attribut : AndereKlasse
  + Methode1()
}
class AndereKlasse {
  - Attribut : Typ
  + Methode2()
}

class AufrufendeKlasse {
  + useKlasse()
}
Schnittstelle <|.. Klasse : implementiert
AufrufendeKlasse ..> Schnittstelle : verwendet
Klasse *-- AndereKlasse : aggregiert
note top of Klasse: Diese Notiz liefert eine nähere\n Beschreibung der Klasse
note top of Schnittstelle: Diese Notiz liefert eine nähere\n Beschreibung der Schnittstelle
@enduml
