@startuml class model
!include puml-theme-doubleslash.puml

title <size:18><color:black> Klassenmodell im //-Design
left to right direction
skinparam Ranksep 1
skinparam Nodesep 10
'hide circle

interface Schnittstelle

class Klasse {
  - Attribut : AndereKlasse
  + Methode1()
}
class AndereKlasse {
  - Attribut : Typ
  + Methode2()
}

class AufrufendeKlasse {
  + useInterface()
}
Schnittstelle <|.. Klasse : implementiert
AufrufendeKlasse ..> Schnittstelle : verwendet
Klasse *-- AndereKlasse : aggregiert
note top of Klasse: Diese Notiz liefert eine nähere\n Beschreibung der Klasse
note top of Schnittstelle: Diese Notiz liefert eine nähere\n Beschreibung der Schnittstelle
@enduml
