@startuml class model
!include ../puml-theme-doubleslash.puml

!define textsize14(name) "<size:14><b>name</size>" as name
left to right direction
'hide circle

title Datenmodell 

entity textsize14(Entität1)  {
    + name : text
    + params : Text[]
    + text2: Text

    e1Id : SERIAL (PK)
    e2Id: INTEGER (FK)
}
note top of Entität1
    Lorem ipsum dolor sit amet, 
    consetetur sadipscing elitr, 
    sed diam nonumy eirmod tempor 
    invidunt ut labore et dolore magna ...
end note



entity textsize14(Entität2) {

    Name : Text
    Beschreibung: Text
    keyvalues: Text[]
    headers: Text[]
    body: Text
    authorizationData: Text

    e2Id : SERIAL (PK)
    apiId : INTEGER (FK)
    otherId: INTEGER (FK)
    collectionId : INTEGER (FK)
}
note top of Entität2
Lorem ipsum dolor sit amet, 
consetetur sadipscing elitr, 
sed diam nonumy eirmod tempor 
invidunt ut labore et dolore magna 
aliquyam erat, sed diam voluptua. 
At vero eos et accusam et justo 
duo dolores et ea rebum. Stet clita 
kasd gubergren, no sea takimata 
sanctus est Lorem ipsum dolor sit amet. 
Lorem ipsum dolor sit amet, consetetur 
sadipscing elitr, sed diam nonumy ...
end note

entity textsize14(CollectionEntity) {
    collectionId : SERIAL (PK)
    name : Text
}

entity textsize14(OtherEntity) <<external>> {
    otherId : SERIAL (PK)
    name : Text
}
note bottom of OtherEntity
    Lorem ipsum dolor sit amet, 
    consetetur sadipscing elitr, 
    sed diam nonumy eirmod tempor 
    invidunt ut labore et dolore magna ...
end note

CollectionEntity |o----o{ Entität2

Entität2 }o---|| Entität1
Entität2 }o---|{ OtherEntity

@enduml




