@startuml piprocess
!include ../puml-theme-doubleslash.puml
'!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash.puml
skinparam padding 4

start 

package Planung {
note left: 

   :doubleSlash Angebot über 
    verfügbare Kapa ab;

   :Kapa wird in StoryPoints 
   umgerechnet (SP=PT/2);

}


package "Entwicklung" {


   (*)
   note left: Start der Entwicklung
   if (Ungeplantes Ereignis) then (Ja)
      :StoryPoints anpassen;
   endif
}

package Abrechnung {
note left: 
   :Erledigte User Stories 
    zusammenzählen;
   :Spill over berechnen;
}
:PI Abschließen;

end


@enduml