@startuml piprocess
!include ../puml-theme-doubleslash.puml
'!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash.puml
skinparam padding 3

skinparam PartitionBorderColor DS_GREY

start

partition Planung {
   note left:

   :doubleSlash Angebot über
   verfügbare Kapa ab;

   :Kapa wird in StoryPoints
   umgerechnet (SP=PT/2);

}

partition "Entwicklung" {

   :Start der Entwicklung;

   if (Effort Changing Event) then (Ja)


   if (Change bewerten) then (Großer Change)
      if() then (Mehraufwand)
       if()
      :StoryPoints erhöhen;
      else
        :Neue User Stories\nanlegen; 
      endif 
      else (Minderaufwand)
      :StoryPoints verringern;
      endif
   else (Kleiner Change)
      :Stories werden mit
      dem vereinbarten
      Aufwand erledigt.;
   endif
   endif

   :Ende der Entwicklung;
}

partition Abrechnung {
   note left:
   :Erledigte StoryPoints
   zusammenzählen;
   :Spill over berechnen;
}
:PI Abschließen;

end


@enduml