@startgantt projectplan
!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/pgantt-theme-doubleslash.puml
'!include ../pgantt-theme-doubleslash.puml
!include input/projectplan.puml
@endgantt