@startgantt projectplan
''Define doubleSlash styling
!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/pgantt-theme-doubleslash.puml

'saturday are closed
'sunday are closed

'printscale weekly

title Projekt Zeitplan in //-Design

2024-01-20 is colored in salmon

Project starts 2024-01-07
[Prototype design] starts 2024-01-15

[Prototype design] lasts 10 days
[Develop prototype] lasts 15 days
[Test prototype] lasts 7 days

[Develop prototype] starts at [Prototype design]'s end
[Develop completed] happens at [Develop prototype]'s end

[Test prototype] starts at [Develop prototype]'s end


[Prototype design] is 100% completed
[Develop prototype] is 60% completed
[Test prototype] is 25% completed

@endgantt