@startuml Sequence model
!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-sequence.puml
'!include ../puml-theme-doubleslash-sequence.puml
!include input/sequencemodel.puml
@enduml