@startuml Sequence model
!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-sequence.puml
	
skinparam maxMessageSize 100
skinparam ParticipantPadding 50

skinparam SequenceLifeLineBorderThickness 15.0
'skinparam SequenceActorBorderThickness 2.0
skinparam ActorBorderThickness 2.0
skinparam SequenceParticipantBorderThickness 0.0

title Sequenzmodell

Actor Alice <<actor>>
Participant FrontEnd <<actor>>
Participant API <<actor>>
Participant Backend <<actor>>
Participant DB <<actor>>



== Initialization ==
Alice -> FrontEnd: klick Button
activate FrontEnd
FrontEnd -> API: call Service
API -> Backend : Call Backend

activate Backend
Backend -> API : return value
deactivate Backend

API -> FrontEnd : return value
FrontEnd -> Alice: Show status
deactivate FrontEnd

== Processing ==
Backend -> DB : read detail data
activate Backend
DB -> Backend : return
Backend -> Backend : process result
Backend -> Alice : send email
deactivate Backend

@enduml