@startuml
!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-system.puml

' Define colors for each C4 level
!define C4_CONTEXT_BG #FFFFFF
!define C4_CONTAINER_BG #EEF8FE
!define C4_FUNCTION_BG #D7E9F4
!define C4_MODULE_BG #AFC1C7
!define C4_CODE_BG #84999F

' Context Level
skinparam RectangleBackgroundColor<<context>> C4_CONTEXT_BG
skinparam RectangleBorderColor<<context>> DS_BLUE
skinparam RectangleFontColor<<context>> black

' Container Level  
skinparam RectangleBackgroundColor<<container>> C4_CONTAINER_BG
skinparam RectangleBorderColor<<container>> white
skinparam RectangleFontColor<<container>> black

' Function Level
skinparam RectangleBackgroundColor<<function>> C4_FUNCTION_BG
skinparam RectangleBorderColor<<function>> white
skinparam RectangleFontColor<<function>> black

' Module Level
skinparam RectangleBackgroundColor<<module>> C4_MODULE_BG
skinparam RectangleBorderColor<<module>> white
skinparam RectangleFontColor<<module>> black

' Code Level
skinparam RectangleBackgroundColor<<code>> C4_CODE_BG
skinparam RectangleBorderColor<<code>> white
skinparam RectangleFontColor<<code>> black
'skinparam nodesep 32
'skinparam ranksep 10


title "System model with C4-Level 1-System context and 2-Containers"


' Definition of objects
rectangle "System context" <<context>> {

    package "Container"  <<container>> {
        rectangle "Component 1" <<function>>
        rectangle "Component 2" <<function>>
    }

    interface "Interface 1" as IF1
    note top of IF1
        This is a short
        description of the interface
    end note

}

agent "Calling System" as No2<<external>>
agent "Other\nlegacy system" as LegacySystem<<external>>
database "External\ndatabase" as eDB<<external>>
interface "Interface 2" as IF2 <<external>>

IF1 <|-- [Component 1] : implements
IF2 <|-- LegacySystem : implements
No2 ~~> IF1 : use

[Component 1] ~~> eDB : use
[Component 2] ~~> IF2 : use

rectangle "legend" <<context>> {
  rectangle "Context" <<context>>
  rectangle "Container " <<container>>
  rectangle "Function" <<function>>
  rectangle "Module" <<module>>
  rectangle "Code" <<code>> 

}
@enduml