@startuml usecase model
!include ../puml-theme-doubleslash.puml
'You will find help here https://plantuml.com/de/use-case-diagram

left to right direction


title Usecase Diagramm im //-Design

Actor "Actor 1" as actor1
Actor "Actor 2" as actor2

rectangle  "System B" {
    UseCase (Second usecase) as UC2
    UseCase (Third usecase) as UC3
} 
rectangle "System A" {
    UseCase (First usecase) as UC1
}

UseCase (Old Usecase) <<External>> as UC4
UseCase (Other Usecase) <<External>> as UC5

actor1  --- UC1

actor2 -- UC1
actor2 -- UC2
actor2 -- UC3
UC3 ..|> UC4 : <<include>>
UC2 <|.. UC5 : <<extends>>

@enduml