@startditaa Activity_Diagram


+-------------------+
|     cBLU          |
|   Start Process   |
|           {o}     |
+-------------------+
          |
          v
+-------------------+          
|                   |    No     /---------------------\    
|   Did you order   | --------> | Call wingstop to    |
|     hot wings?{c} |           | order hot wings     |
|        cRED       |           \---------------------/
+-------------------+                  |
          | Yes                        |
          v                            |
/-------------------\                  |
|  Eat Hotwings     | <----------------+
\-------------------/
          |
          v
+-------------------+         
|      cRED         |   No      /---------------------\
|   Do you need milk| --------> | Eat more wings      |
|   to cool down?   |           |                     |
|           {c}     |           \---------------------/
+-------------------+                |
          |     ^                    |
          |Yes  |                    |
          |     +--------------------+
          |
          v
/-------------------\        
|  Drink Milk       |            
\-------------------/          
          |                       
          v                       
+-------------------+     
|     cRED          |   No    /-------------------\
|   Are you still   | ------->|      cGRE         |
|      hungry?      |         |    End Process    |
|        {c}        |         |           {o}     |             
+-------------------+         \-------------------/
          | Yes                       
          v                           
/-------------------\            
|  Order more Wings | 
|                   |
\-------------------/
          |
          v
+-------------------+
|     cGRE          |
|    End Process    |
|        {o}        |
+-------------------+

@endditaa