@startuml Aws_Icons_2

scale 1
skinparam linetype ortho
left to right direction

!include <awslib/AWSCommon>
'!include <awslib/AWSSimplified>
!include <awslib/Groups/AWSCloud>
!include <awslib/Groups/VPC>
!include <awslib/Groups/Generic>
!include <awslib/General/Users>
!include <awslib/SecurityIdentityCompliance/Cognito>
!include <awslib/NetworkingContentDelivery/ElasticLoadBalancing>
!include <awslib/Compute/EC2>
!include <awslib/Database/RDS>
!include <awslib/Compute/Lambda>
!include <awslib/Storage/SimpleStorageService>

Users(sources1, "Users", "Americas")
Users(sources2, "Users", "Asia")
Users(sources3, "Users", "Europe")

AWSCloudGroup(cloud) {

  Cognito(userAuth, "User Auth", "JWT")

  VPCGroup(vpc) {
    
    ElasticLoadBalancing(elb, "ELB", "ALB")
    
    GenericGroup(target, "Target Group") {
      EC2(ec21, "EC2", "2")
      EC2(ec22, "EC2", "1")
    }
    
    RDS(rds, "RDS", "Postgresql")
  }
  
  Lambda(lambda, "AWS Lambda", "C#")
  SimpleStorageService(s3, "Amazon S3", "aws-bucket")
}

sources1 --> userAuth
sources2 --> userAuth
sources3 --> userAuth
userAuth --> elb
elb --> ec21
elb --> ec22
ec21 --> rds
ec22 -> rds
elb .right.> lambda
lambda .down.> s3

@enduml