@startuml activitymodel
!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-activity.puml
'!include ../../puml-theme-doubleslash-activity.puml
!include ../input/activity/19 - Activity Model.puml
@enduml