@startuml class model
!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-class.puml
'!include ../../puml-theme-doubleslash-class.puml
!include ../input/class/20 - Class Model.puml
@enduml