@startuml
!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-system.puml
'!include ../../puml-theme-doubleslash-system.puml
!include ../input/systemmodel with levels.puml
@enduml