@startuml usecase model
!include https://raw.githubusercontent.com/doubleSlashde/umltheme/main/puml-theme-doubleslash-usecase.puml
'!include ../../puml-theme-doubleslash-usecase.puml
!include ../input/usecase 2.puml
@enduml